-- The same request, rewritten after the BLOCK: ZIP generalized to 3 digits, birth date to a decade,
-- and groups smaller than 5 people are dropped. Expected verdict: PASS.
CREATE OR REPLACE VIEW LEAKHUNTER.DATA.PATIENT_ANALYTICS AS
SELECT LEFT(P.ZIP, 3) AS ZIP3,
       FLOOR(YEAR(P.DOB) / 10) * 10 AS BIRTH_DECADE,
       P.SEX,
       V.DIAGNOSIS_DESC,
       COUNT(*) AS PATIENTS
FROM LEAKHUNTER.DATA.PATIENTS P
JOIN LEAKHUNTER.DATA.VISITS V ON V.PATIENT_ID = P.PATIENT_ID
GROUP BY 1, 2, 3, 4
HAVING COUNT(*) >= 5;

GRANT SELECT ON VIEW LEAKHUNTER.DATA.PATIENT_ANALYTICS TO ROLE LH_ANALYST;
