-- LeakHunter · 00_setup.sql · run once in a Snowsight worksheet, top to bottom.
-- Requires an ENTERPRISE edition trial (masking + row access policies need it).
-- Safe to re-run (IF NOT EXISTS / OR REPLACE everywhere).

------------------------------------------------------------------
-- A. Account level (ACCOUNTADMIN)
------------------------------------------------------------------
USE ROLE ACCOUNTADMIN;

-- Lets CoCo and AI_COMPLETE use models from any region.
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

CREATE WAREHOUSE IF NOT EXISTS LH_WH
  WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

CREATE ROLE IF NOT EXISTS LH_ADMIN;
CREATE ROLE IF NOT EXISTS LH_ANALYST;
CREATE ROLE IF NOT EXISTS LH_HR;
GRANT ROLE LH_ADMIN TO ROLE SYSADMIN;          -- so your own login can USE ROLE LH_ADMIN
-- LH_ADMIN must own LH_HR so it can plant L4 (GRANT ROLE LH_HR TO ROLE LH_ANALYST) and the
-- defender can revoke it. Only a role's owner can grant/revoke it. (Ownership != inheritance:
-- LH_ADMIN does NOT get LH_HR's privileges, and LH_ANALYST does NOT get LH_ADMIN's.)
GRANT OWNERSHIP ON ROLE LH_HR TO ROLE LH_ADMIN COPY CURRENT GRANTS;

GRANT USAGE, OPERATE ON WAREHOUSE LH_WH TO ROLE LH_ADMIN;
GRANT USAGE ON WAREHOUSE LH_WH TO ROLE LH_ANALYST;
GRANT USAGE ON WAREHOUSE LH_WH TO ROLE LH_HR;

GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE LH_ADMIN;
GRANT APPLY ROW ACCESS POLICY ON ACCOUNT TO ROLE LH_ADMIN;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE LH_ADMIN;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE LH_ANALYST;   -- chatbot stretch

CREATE DATABASE IF NOT EXISTS LEAKHUNTER;
GRANT OWNERSHIP ON DATABASE LEAKHUNTER TO ROLE LH_ADMIN COPY CURRENT GRANTS;

-- Service user for scripts (key added after generating it; see docs/CONTRACTS.md §10)
CREATE USER IF NOT EXISTS LH_BOT
  TYPE = SERVICE
  DEFAULT_ROLE = LH_ADMIN
  DEFAULT_WAREHOUSE = LH_WH
  COMMENT = 'LeakHunter scripts';
GRANT ROLE LH_ADMIN TO USER LH_BOT;
GRANT ROLE LH_ANALYST TO USER LH_BOT;
-- ALTER USER LH_BOT SET RSA_PUBLIC_KEY = '<paste .pub body here>';

-- Optional: Snowsight logins for teammates (they set their own password + MFA on first login)
-- CREATE USER IF NOT EXISTS MANAS PASSWORD = '<temp>' MUST_CHANGE_PASSWORD = TRUE DEFAULT_ROLE = LH_ADMIN DEFAULT_WAREHOUSE = LH_WH;
-- CREATE USER IF NOT EXISTS REYA  PASSWORD = '<temp>' MUST_CHANGE_PASSWORD = TRUE DEFAULT_ROLE = LH_ADMIN DEFAULT_WAREHOUSE = LH_WH;
-- GRANT ROLE LH_ADMIN TO USER MANAS;  GRANT ROLE LH_ADMIN TO USER REYA;

-- After getting "Snowflake Public Data (Free)" from Marketplace, fill in its database name:
-- GRANT IMPORTED PRIVILEGES ON DATABASE <PUBLIC_DB_NAME> TO ROLE LH_ADMIN;
-- GRANT IMPORTED PRIVILEGES ON DATABASE <PUBLIC_DB_NAME> TO ROLE LH_ANALYST;

------------------------------------------------------------------
-- B. Project objects (LH_ADMIN owns everything)
------------------------------------------------------------------
USE ROLE LH_ADMIN;
USE WAREHOUSE LH_WH;
USE DATABASE LEAKHUNTER;

CREATE SCHEMA IF NOT EXISTS DATA;
CREATE SCHEMA IF NOT EXISTS SCRATCH;
CREATE SCHEMA IF NOT EXISTS GOVERNANCE;
CREATE SCHEMA IF NOT EXISTS RESULTS;

-- Baseline access. Table-level SELECT grants for the analyst are made by setup/ after tables exist.
GRANT USAGE ON DATABASE LEAKHUNTER TO ROLE LH_ANALYST;
GRANT USAGE ON SCHEMA LEAKHUNTER.DATA TO ROLE LH_ANALYST;
GRANT USAGE ON DATABASE LEAKHUNTER TO ROLE LH_HR;
GRANT USAGE ON SCHEMA LEAKHUNTER.DATA TO ROLE LH_HR;

------------------------------------------------------------------
-- C. Results tables + views (contract: docs/CONTRACTS.md §8)
------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS RESULTS.ATTACK_RUNS (
  RUN_ID STRING, ROUND_NO INT, ATTACK_ID STRING, GOAL STRING, TECHNIQUE STRING, SOURCE STRING,
  TARGETS_LEAK STRING, SQL_TEXT STRING, SUCCEEDED BOOLEAN, ROWS_RETURNED INT,
  EVIDENCE STRING, ERROR STRING, RAN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RESULTS.LEGIT_RUNS (
  RUN_ID STRING, ROUND_NO INT, QUERY_ID STRING, DESCRIPTION STRING, PASSED BOOLEAN,
  ERROR STRING, RAN_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RESULTS.FIXES (
  FIX_ID STRING, ROUND_NO INT, ATTACK_ID STRING, FIX_TYPE STRING, SQL_APPLIED STRING,
  RATIONALE STRING, APPLIED_BY STRING, APPLIED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RESULTS.PLANTED (
  LEAK_ID STRING, DESCRIPTION STRING, PLANTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE VIEW RESULTS.LEAK_LOG AS
SELECT *
FROM RESULTS.ATTACK_RUNS
WHERE SUCCEEDED
  AND ROUND_NO = (SELECT MAX(ROUND_NO) FROM RESULTS.ATTACK_RUNS);

CREATE OR REPLACE VIEW RESULTS.SCOREBOARD AS
WITH A AS (
  SELECT ROUND_NO,
         COUNT(DISTINCT IFF(SUCCEEDED, ATTACK_ID, NULL)) AS LEAKS,
         COUNT(DISTINCT ATTACK_ID)                       AS ATTACKS
  FROM RESULTS.ATTACK_RUNS GROUP BY ROUND_NO
), L AS (
  SELECT ROUND_NO,
         COUNT_IF(PASSED) AS LEGIT_PASSED,
         COUNT(*)         AS LEGIT_TOTAL
  FROM RESULTS.LEGIT_RUNS GROUP BY ROUND_NO
)
SELECT COALESCE(A.ROUND_NO, L.ROUND_NO) AS ROUND_NO, A.LEAKS, A.ATTACKS, L.LEGIT_PASSED, L.LEGIT_TOTAL
FROM A FULL OUTER JOIN L ON A.ROUND_NO = L.ROUND_NO
ORDER BY ROUND_NO;

------------------------------------------------------------------
-- D. Masking policies (created now, NOT applied — applying them is the defender's job)
------------------------------------------------------------------
CREATE MASKING POLICY IF NOT EXISTS GOVERNANCE.MASK_SSN AS (VAL STRING) RETURNS STRING ->
  CASE WHEN IS_ROLE_IN_SESSION('LH_ADMIN') THEN VAL ELSE '***-**-' || RIGHT(VAL, 4) END;

CREATE MASKING POLICY IF NOT EXISTS GOVERNANCE.MASK_NAME AS (VAL STRING) RETURNS STRING ->
  CASE WHEN IS_ROLE_IN_SESSION('LH_ADMIN') THEN VAL ELSE 'REDACTED' END;

CREATE MASKING POLICY IF NOT EXISTS GOVERNANCE.MASK_ZIP AS (VAL STRING) RETURNS STRING ->
  CASE WHEN IS_ROLE_IN_SESSION('LH_ADMIN') THEN VAL ELSE LEFT(VAL, 3) || '00' END;

CREATE MASKING POLICY IF NOT EXISTS GOVERNANCE.MASK_DOB AS (VAL DATE) RETURNS DATE ->
  CASE WHEN IS_ROLE_IN_SESSION('LH_ADMIN') THEN VAL ELSE DATE_FROM_PARTS(YEAR(VAL), 1, 1) END;

-- Sanity check (expect: 4 schemas + INFORMATION_SCHEMA/PUBLIC, 4 policies, LH_HR owned by LH_ADMIN)
SHOW SCHEMAS IN DATABASE LEAKHUNTER;
SHOW MASKING POLICIES IN SCHEMA LEAKHUNTER.GOVERNANCE;
SHOW ROLES LIKE 'LH_%';
SELECT * FROM RESULTS.SCOREBOARD;

------------------------------------------------------------------
-- E. Bouncer log (skills/bouncer) — contract: docs/CONTRACTS.md §8
------------------------------------------------------------------
USE ROLE LH_ADMIN;
CREATE TABLE IF NOT EXISTS LEAKHUNTER.RESULTS.BOUNCER_LOG (
  CHECK_ID STRING, PACKAGE STRING, ECOSYSTEM STRING, VERDICT STRING, REASONS STRING,
  REQUESTED_BY STRING, CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
